version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-6b2nle^d2p3#w3lka_!&&q1_w1mn5$oi7&d+)_v0^8s^7*c#y6
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: